// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// committing this file to github, original file name is generates with
/// the name 'firebase_options.dart',
/// this file is for reference purose

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'apiKey',
    appId: 'appId',
    messagingSenderId: '488225459821',
    projectId: 'mynotes-flutter-f6adf',
    authDomain: 'mynotes-flutter-f6adf.firebaseapp.com',
    storageBucket: 'mynotes-flutter-f6adf.firebasestorage.app',
    measurementId: 'G-SMLKBPYW69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'apiKey',
    appId: 'appId',
    messagingSenderId: '488225459821',
    projectId: 'mynotes-flutter-f6adf',
    storageBucket: 'mynotes-flutter-f6adf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'apiKey',
    appId: 'appId',
    messagingSenderId: '488225459821',
    projectId: 'mynotes-flutter-f6adf',
    storageBucket: 'mynotes-flutter-f6adf.firebasestorage.app',
    iosBundleId: 'org.sharathchandra.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'apiKey',
    appId: 'appId',
    messagingSenderId: '488225459821',
    projectId: 'mynotes-flutter-f6adf',
    storageBucket: 'mynotes-flutter-f6adf.firebasestorage.app',
    iosBundleId: 'org.sharathchandra.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'apiKey',
    appId: 'appId',
    messagingSenderId: '488225459821',
    projectId: 'mynotes-flutter-f6adf',
    authDomain: 'mynotes-flutter-f6adf.firebaseapp.com',
    storageBucket: 'mynotes-flutter-f6adf.firebasestorage.app',
    measurementId: 'G-B4HM3XVSWJ',
  );

}